name: Publish RTB.Styled

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/RTB.Styled/**'
      - '.github/workflows/nuget-publish-styled.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore src/RTB.Styled/RTB.Styled.csproj

      - name: Build
        run: dotnet build src/RTB.Styled/RTB.Styled.csproj --configuration Release

      - name: Pack
        run: dotnet pack src/RTB.Styled/RTB.Styled.csproj --configuration Release
        
      - name: Publish to nuget.org
        run: dotnet nuget push "src/RTB.Styled/bin/Release/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate